### ISSUE TITLE
Is accuracy raise up depends on parameter numbers?

### ISSUE THREAD

**Issue by dreambear1234** [wallarm/nascell-automl#4]
There are several confused problem, Could you help me?
1. In your code, the function CNN(), used conv1d and max_pooling1d, It will lose spatial information, as my point, 3*3 conv is more useful. why don't you use 2d conv and pooling?

2. as last issue talk about, the calculation of reward is confused, https://github.com/wallarm/nascell-automl/issues/3 ; 

3. Does reward never be negative is fine?

4. In the code, output number is 4*2, [kernel_size, filter_num, pooling_size, drop_ratio]*2; It seems that drop ratio is never used?

Thank you very much!

**Comment by mdsalnikov** [comment]
Sorry that I answer so late

1. Of course, you are right, but I use 1d because it worked faster and goal of this project is just example of AutoML. 
2. First acc is reward, second is current accuracy. If new acc < previously acc, we return 0.01 - reward of error. Well, I need more clearer question) 
3. I just picked up the optimum reward for error by hand. Negative reward leads us to unnormal states like [-100, -100, -100, -100].
4. My tests showed that it is not. In the later stages of learning, I was getting a dropout_rate ~= 0.85.

Thanks for your issue!

**Comment by mdsalnikov** [comment]
So, I close this issue. if you have some question about it, please reopen.
